[k3s_server]
i-0cda7c33c95783b2b ansible_connection=aws_ssm ansible_aws_ssm_region=eu-west-1 ansible_aws_ssm_bucket_name=ansiblebucketriztestnow ansible_shell_type=sh

[k3s_agent]
i-0e7f3d57bf234a0d4 ansible_connection=aws_ssm ansible_aws_ssm_region=eu-west-1 ansible_aws_ssm_bucket_name=ansiblebucketriztestnow ansible_shell_type=sh

[all:vars]
ansible_python_interpreter=/usr/bin/python3
