[k3s_server]
i-REPLACE_WITH_SERVER_ID ansible_connection=aws_ssm ansible_aws_ssm_region=eu-west-1 ansible_aws_ssm_bucket_name=REPLACE_WITH_BUCKET_NAME ansible_shell_type=sh

[k3s_agent]
i-REPLACE_WITH_AGENT_ID ansible_connection=aws_ssm ansible_aws_ssm_region=eu-west-1 ansible_aws_ssm_bucket_name=REPLACE_WITH_BUCKET_NAME ansible_shell_type=sh

[all:vars]
ansible_python_interpreter=/usr/bin/python3
